version: '3.7'

services:

  money_lender_db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=credit_user
      - POSTGRES_PASSWORD=credit_password
      - POSTGRES_DB=credit_db

  money_lender:
    build:
      context: .
      dockerfile: Dockerfile
#    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app/web
    environment:
      - DATABASE_URL=postgresql://credit_user:credit_password@money_lender_db:5432/credit_db
    depends_on:
      - money_lender_db

volumes:
  postgres_data: